const REPASSES_KEY='jeri-rota-manager-repasses-v1';
const TOURS_KEY='jeri-rota-manager-passeios-v1';
const LOCATIONS_KEY='jeri-rota-manager-locais-v1';
const STATUS=['Pendente','Enviado','Confirmado','Finalizado'];
const DEFAULT_TOURS=['Litoral Leste','Litoral Oeste'];
const $=id=>document.getElementById(id);
const currency=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const todayFormat=new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short'});

function read(key,fallback=[]){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHtml(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__jrToast);window.__jrToast=setTimeout(()=>el.classList.remove('show'),1800)}
function normalizeMoney(v){const s=String(v||'').replace(/[^\d,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?Math.max(0,n):0}
function brDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}/${m}/${y}`}
function mapUrl(query){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`}

function getTours(){let tours=read(TOURS_KEY);if(!tours.length){tours=[...DEFAULT_TOURS];write(TOURS_KEY,tours)}return tours}
function getLocations(){return read(LOCATIONS_KEY)}
function getRepasses(){return read(REPASSES_KEY)}
function nextNumber(){return getRepasses().reduce((m,x)=>Math.max(m,Number(x.number)||0),0)+1}
function nextCode(){return `REP-${String(nextNumber()).padStart(5,'0')}`}

function renderTours(){const tours=getTours().slice().sort((a,b)=>a.localeCompare(b,'pt-BR'));$('tourSelect').innerHTML='<option value="">Selecione...</option>'+tours.map(t=>`<option>${escapeHtml(t)}</option>`).join('');$('tourList').innerHTML=tours.map(t=>`<div class="catalog-item"><div><strong>${escapeHtml(t)}</strong><small>Disponível nos novos repasses</small></div><div class="catalog-actions"><button class="mini-button" data-tour-edit="${encodeURIComponent(t)}">Editar</button><button class="mini-button" data-tour-delete="${encodeURIComponent(t)}">Excluir</button></div></div>`).join('');$('tourEmpty').style.display=tours.length?'none':'block'}
function renderLocations(){const items=getLocations().slice().sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));$('boardingOptions').innerHTML=items.map(x=>`<option value="${escapeHtml(x.name)}">${escapeHtml(x.address||x.type||'')}</option>`).join('');$('locationList').innerHTML=items.map(x=>`<div class="catalog-item"><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml([x.type,x.address].filter(Boolean).join(' · '))}</small></div><div class="catalog-actions"><button class="mini-button maps" data-location-maps="${x.id}">Maps</button><button class="mini-button" data-location-edit="${x.id}">Editar</button><button class="mini-button" data-location-delete="${x.id}">Excluir</button></div></div>`).join('');$('locationEmpty').style.display=items.length?'none':'block'}

function formData(){return{date:$('serviceDate').value,tour:$('tourSelect').value,boarding:$('boardingInput').value.trim(),names:$('namesInput').value.trim(),phone:$('phoneInput').value.trim(),people:Math.max(1,Number($('peopleInput').value)||1),amount:normalizeMoney($('amountInput').value)}}
function message(data,code){return `Código: ${code}\nData: ${brDate(data.date)}\nPasseio: ${data.tour}\nEmbarque: ${data.boarding}\nPassageiro(s): ${data.names}\nTelefone: ${data.phone}\nQuantidade: ${data.people} pessoa${data.people===1?'':'s'}\nValor a receber: ${currency.format(data.amount)}`}
function updatePreview(){const data=formData();$('nextCode').textContent=nextCode();const has=data.date||data.tour||data.boarding||data.names||data.phone||data.amount;if(!has){$('messagePreview').className='message-preview empty';$('messagePreview').textContent='Preencha os dados para visualizar a mensagem.';return}$('messagePreview').className='message-preview';$('messagePreview').textContent=message(data,nextCode())}
function syncPeopleFromNames(){const names=$('namesInput').value.trim();const people=names?((names.match(/\//g)||[]).length+1):1;$('peopleInput').value=people;updatePreview()}
function maybeSaveLocation(name){if(!$('saveLocationCheck').checked||!name)return;const items=getLocations();if(items.some(x=>x.name.toLowerCase()===name.toLowerCase()))return;items.push({id:Date.now(),name,type:'Hotel / pousada',address:''});write(LOCATIONS_KEY,items);renderLocations()}
function createRepasse(openWhatsapp){if(!$('repasseForm').reportValidity())return;const data=formData();const number=nextNumber();const item={id:Date.now(),number,code:`REP-${String(number).padStart(5,'0')}`,...data,status:openWhatsapp?'Enviado':'Pendente',createdAt:new Date().toISOString()};const items=getRepasses();items.unshift(item);write(REPASSES_KEY,items);maybeSaveLocation(data.boarding);if(openWhatsapp)window.open(`https://wa.me/?text=${encodeURIComponent(message(item,item.code))}`,'_blank');$('repasseForm').reset();$('peopleInput').value=1;renderHistory();updatePreview();toast(openWhatsapp?'Repasse salvo e WhatsApp aberto.':'Repasse salvo.')}

function renderHistory(){const q=$('historySearch').value.trim().toLowerCase();const status=$('historyStatus').value;const items=getRepasses().filter(x=>{const text=`${x.code} ${x.names} ${x.tour} ${x.phone} ${x.boarding}`.toLowerCase();return(!q||text.includes(q))&&(!status||x.status===status)});$('historyBody').innerHTML=items.map(x=>`<tr><td><strong>${x.code}</strong></td><td>${brDate(x.date)}</td><td>${escapeHtml(x.tour)}</td><td>${escapeHtml(x.boarding)}<small><a href="${mapUrl(x.boarding)}" target="_blank" rel="noopener">Ver no Maps</a></small></td><td>${escapeHtml(x.names)}</td><td>${x.people}</td><td><strong>${currency.format(x.amount)}</strong></td><td><span class="status-pill status-${x.status.toLowerCase()}">${x.status}</span></td><td><div class="repasse-row-actions"><button class="mini-button maps" data-repasse-wa="${x.id}">WhatsApp</button><button class="mini-button" data-repasse-status="${x.id}">Avançar</button><button class="mini-button" data-repasse-delete="${x.id}">Excluir</button></div></td></tr>`).join('');$('historyEmpty').style.display=items.length?'none':'block'}

$('repasseForm').addEventListener('submit',e=>{e.preventDefault();createRepasse(false)});$('saveWhatsappButton').addEventListener('click',()=>createRepasse(true));['serviceDate','tourSelect','boardingInput','phoneInput','peopleInput','amountInput'].forEach(id=>{$(id).addEventListener('input',updatePreview);$(id).addEventListener('change',updatePreview)});$('namesInput').addEventListener('input',syncPeopleFromNames);$('namesInput').addEventListener('change',syncPeopleFromNames);$('copyMessageButton').addEventListener('click',async()=>{if($('messagePreview').classList.contains('empty'))return;await navigator.clipboard.writeText($('messagePreview').textContent);toast('Mensagem copiada.')});
$('searchMapsButton').addEventListener('click',()=>{const q=$('boardingInput').value.trim();if(!q)return toast('Digite o local primeiro.');window.open(mapUrl(`${q}, Jericoacoara, Ceará`),'_blank')});

$('tourForm').addEventListener('submit',e=>{e.preventDefault();const name=$('newTourInput').value.trim();if(!name)return;const items=getTours();if(items.some(x=>x.toLowerCase()===name.toLowerCase()))return toast('Esse passeio já está cadastrado.');items.push(name);write(TOURS_KEY,items);$('newTourInput').value='';renderTours();toast('Passeio cadastrado.')});
$('tourList').addEventListener('click',e=>{const edit=e.target.dataset.tourEdit,del=e.target.dataset.tourDelete;if(edit){const old=decodeURIComponent(edit),novo=prompt('Novo nome do passeio:',old);if(novo===null||!novo.trim())return;const items=getTours();const idx=items.indexOf(old);if(idx>=0){items[idx]=novo.trim();write(TOURS_KEY,items);renderTours();toast('Passeio atualizado.')}}if(del){const name=decodeURIComponent(del);if(confirm(`Excluir "${name}"?`)){write(TOURS_KEY,getTours().filter(x=>x!==name));renderTours();toast('Passeio excluído.')}}});

$('newLocationMaps').addEventListener('click',()=>{const name=$('newLocationName').value.trim(),address=$('newLocationAddress').value.trim();if(!name&&!address)return toast('Digite um nome ou endereço.');window.open(mapUrl([name,address,'Jericoacoara, Ceará'].filter(Boolean).join(', ')),'_blank')});
$('locationForm').addEventListener('submit',e=>{e.preventDefault();const name=$('newLocationName').value.trim(),type=$('newLocationType').value,address=$('newLocationAddress').value.trim();const items=getLocations();if(items.some(x=>x.name.toLowerCase()===name.toLowerCase()))return toast('Esse local já está cadastrado.');items.push({id:Date.now(),name,type,address});write(LOCATIONS_KEY,items);e.target.reset();renderLocations();toast('Local salvo.')});
$('locationList').addEventListener('click',e=>{const maps=Number(e.target.dataset.locationMaps),edit=Number(e.target.dataset.locationEdit),del=Number(e.target.dataset.locationDelete),items=getLocations();if(maps){const x=items.find(i=>i.id===maps);if(x)window.open(mapUrl([x.name,x.address].filter(Boolean).join(', ')),'_blank')}if(edit){const x=items.find(i=>i.id===edit);if(!x)return;const name=prompt('Nome do local:',x.name);if(name===null||!name.trim())return;const address=prompt('Endereço ou referência:',x.address||'');x.name=name.trim();x.address=(address||'').trim();write(LOCATIONS_KEY,items);renderLocations();toast('Local atualizado.')}if(del){const x=items.find(i=>i.id===del);if(x&&confirm(`Excluir "${x.name}"?`)){write(LOCATIONS_KEY,items.filter(i=>i.id!==del));renderLocations();toast('Local excluído.')}}});

$('historyBody').addEventListener('click',e=>{const wa=Number(e.target.dataset.repasseWa),advance=Number(e.target.dataset.repasseStatus),del=Number(e.target.dataset.repasseDelete);let items=getRepasses();if(wa){const x=items.find(i=>i.id===wa);if(!x)return;if(x.status==='Pendente')x.status='Enviado';write(REPASSES_KEY,items);window.open(`https://wa.me/?text=${encodeURIComponent(message(x,x.code))}`,'_blank');renderHistory()}if(advance){const x=items.find(i=>i.id===advance);if(!x)return;const p=STATUS.indexOf(x.status);x.status=STATUS[Math.min(p+1,STATUS.length-1)];write(REPASSES_KEY,items);renderHistory();toast('Status atualizado.')}if(del){const x=items.find(i=>i.id===del);if(x&&confirm(`Excluir ${x.code}?`)){write(REPASSES_KEY,items.filter(i=>i.id!==del));renderHistory();updatePreview();toast('Repasse excluído.')}}});
$('historySearch').addEventListener('input',renderHistory);$('historyStatus').addEventListener('change',renderHistory);

document.querySelectorAll('.repasse-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.repasse-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.repasse-panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');$(`tab-${button.dataset.tab}`).classList.add('active')}));
$('menuButton').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
$('todayLabel').textContent=todayFormat.format(new Date()).replace('.','');
renderTours();renderLocations();renderHistory();updatePreview();